import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg'],
      manifest: {
        name: 'DFO Drone Logbook',
        short_name: 'DFO Log',
        description: 'Offline drone flight logging for DFO officers',
        theme_color: '#004c2c',
        background_color: '#ffffff',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '.',
        icons: [
          {
            src: 'icons/icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any maskable'
          },
          {
            src: 'icons/icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable'
          }
        ],
        screenshots: [
          {
            src: 'screenshots/screenshot-mobile.png',
            sizes: '540x720',
            type: 'image/png',
            form_factor: 'narrow'
          },
          {
            src: 'screenshots/screenshot-wide.png',
            sizes: '1200x800',
            type: 'image/png',
            form_factor: 'wide'
          }
        ]
      },
      workbox: {
        // This is critical: it forces the SW to cache everything generated by the build
        globPatterns: ['**/*.{js,css,html,ico,png,svg,json}'],
        // Increase the limit if you have large assets (like that wasm file if you kept it)
        maximumFileSizeToCacheInBytes: 5000000 
      }
    })
  ],
})